FROM php:8.5-cli

WORKDIR /app

COPY . .

RUN apt-get update \
 && apt-get install -y git unzip \
 && docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer install

RUN cp .env.example .env
RUN chmod -R 777 storage bootstrap/cache

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]